# Generated by Django 3.2.4 on 2021-07-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0004_rename_workflowrun_notebookrunlogs_workflowrunlogs'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkflowRun',
            new_name='WorkflowRunLogs',
        ),
    ]
