# Generated by Django 3.1.8 on 2021-04-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20210421_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='dependsOnWorkflow',
            new_name='triggerWorkflow',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='dependsOnWorkflowStatus',
            new_name='triggerWorkflowStatus',
        ),
    ]
