# Generated by Django 3.2.4 on 2021-12-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('workflows', '0002_rename_workflowrun_workflowrunlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='periodictask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
    ]
