# Generated by Django 3.2 on 2021-05-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_auto_20210426_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='triggerWorkflowStatus',
            field=models.CharField(default='SUCCESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=50),
        ),
    ]
