# Generated by Django 3.2 on 2021-05-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_auto_20210509_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='taskId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
