# Generated by Django 3.2.1 on 2021-06-07 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowrun_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='triggerWorkflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow'),
        ),
    ]
