# Generated by Django 3.2.4 on 2021-07-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceconfig',
            name='warehouseLocation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
