version: '3.3'

services:
  cuelake-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    stdin_open: true
    network_mode:
      host
    # networks:
    #   - cuelake-net1
    volumes:
      - ./ui:/app
      - /app/node_modules
  cuelake-api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
    ports:
      - "8000:8000"
    stdin_open: true
    depends_on:
      - postgres
      - redis
    network_mode:
      host
    # networks:
    #   - cuelake-net1
    volumes:
      - ./api:/code
      # Directory of your kube config
      - ~/.kube:/.kube
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/pg_data
      - POSTGRES_DB=cuelake
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /pg_data
    network_mode:
      host
    # networks:
    #   - cuelake-net1
  redis:
    ports:
      - "6379:6379"
    image: "redis:alpine"
    network_mode:
      host
    # networks:
    #   - cuelake-net1

# networks:
#   cuelake-net1:
#     internal: true