# Generated by Django 3.2.4 on 2021-07-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstatus',
            name='updateTimestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
