# Generated by Django 3.1.7 on 2021-03-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookjob',
            name='notebookId',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RunStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('logs', models.TextField(default='{}')),
                ('status', models.CharField(max_length=7)),
                ('notebookJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genie.notebookjob')),
            ],
        ),
    ]
