# Generated by Django 3.2.4 on 2021-10-30 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        ('workspace', '0001_initial'),
        ('genie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookrunlogs',
            name='workflowRunLogs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowrunlogs'),
        ),
        migrations.AddField(
            model_name='notebookrunlogs',
            name='workspace',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='notebookobject',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genie.connection'),
        ),
        migrations.AddField(
            model_name='notebookobject',
            name='notebookTemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genie.notebooktemplate'),
        ),
        migrations.AddField(
            model_name='connectionparamvalue',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpvc', to='genie.connection'),
        ),
        migrations.AddField(
            model_name='connectionparamvalue',
            name='connectionParam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpvcp', to='genie.connectionparam'),
        ),
        migrations.AddField(
            model_name='connectionparam',
            name='connectionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectionTypeParam', to='genie.connectiontype'),
        ),
        migrations.AddField(
            model_name='connection',
            name='connectionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectionTypeConnection', to='genie.connectiontype'),
        ),
        migrations.AddField(
            model_name='connection',
            name='workspace',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
    ]
