# Generated by Django 3.2.4 on 2021-11-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0002_runstatus_updatetimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookobject',
            name='retryCount',
            field=models.IntegerField(default=0),
        ),
    ]
