# Generated by Django 3.2.4 on 2021-07-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        ('genie', '0002_runstatus_updatetimestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunStatus',
            new_name='NotebookRunLogs',
        ),
    ]
