# Generated by Django 3.1.7 on 2021-04-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0002_auto_20210318_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runstatus',
            old_name='timestamp',
            new_name='startTimestamp',
        ),
        migrations.AddField(
            model_name='runstatus',
            name='endTimestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='runstatus',
            name='message',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
