# Generated by Django 3.2.4 on 2021-07-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0002_runstatus_updatetimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookobject',
            name='defaultPayload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='notebooktemplate',
            name='formJson',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='notebooktemplate',
            name='template',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='runstatus',
            name='logs',
            field=models.TextField(default=dict),
        ),
    ]
