# Generated by Django 3.2.4 on 2021-07-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0003_rename_runstatus_notebookrunlogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebookrunlogs',
            old_name='workflowRun',
            new_name='workflowRunLogs',
        ),
    ]
