# Generated by Django 3.2.4 on 2021-11-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0003_notebookobject_retrycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstatus',
            name='retryRemaining',
            field=models.IntegerField(default=0),
        ),
    ]
