# Generated by Django 3.1.7 on 2021-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0004_auto_20210414_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionparam',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
