# Generated by Django 3.2.4 on 2021-11-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0004_runstatus_retryremaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookobject',
            name='notebookTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genie.notebooktemplate'),
        ),
    ]
