# Generated by Django 3.2.4 on 2021-11-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0004_rename_workflowrun_notebookrunlogs_workflowrunlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookobject',
            name='retryCount',
            field=models.IntegerField(default=0),
        ),
    ]
