# Generated by Django 3.1.7 on 2021-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0006_notebooktemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runstatus',
            name='notebookJob',
        ),
        migrations.AddField(
            model_name='runstatus',
            name='notebookId',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='runstatus',
            name='runType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='runstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
