# Generated by Django 3.2 on 2021-04-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('genie', '0007_auto_20210417_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.crontabschedule')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('django_celery_beat.crontabschedule',),
        ),
    ]
