# Generated by Django 3.2 on 2021-05-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0008_runstatus_worflowrun'),
        ('genie', '0008_schedule'),
    ]

    operations = [
    ]
