# Generated by Django 3.2 on 2021-05-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('genie', '0009_merge_0008_runstatus_worflowrun_0008_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='CustomSchedule',
        ),
    ]
