# Generated by Django 3.2 on 2021-05-12 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0010_rename_schedule_customschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebookZeppelinId', models.CharField(max_length=10)),
                ('defaultPayload', models.JSONField(default={})),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genie.connection')),
                ('notebookTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genie.notebooktemplate')),
            ],
        ),
    ]
