# Generated by Django 3.2.1 on 2021-05-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0011_alter_runstatus_worflowrun'),
        ('genie', '0011_auto_20210512_0226'),
    ]

    operations = [
    ]
