# Generated by Django 3.2 on 2021-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0012_merge_20210513_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstatus',
            name='taskId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
