# Generated by Django 3.2 on 2021-05-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0013_runstatus_taskid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runstatus',
            old_name='worflowRun',
            new_name='workflowRun',
        ),
    ]
