# Generated by Django 3.2.1 on 2021-06-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowrun_taskid'),
        ('genie', '0014_rename_worflowrun_runstatus_workflowrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstatus',
            name='workflowRun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowrun'),
        ),
    ]
