# Generated by Django 3.2.1 on 2021-06-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0015_alter_runstatus_workflowrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstatus',
            name='zeppelinServerId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
