kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zeppelin-server-{workspaceName}-pvc
  namespace: {podNamespace}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem