# Generated by Django 3.1.7 on 2021-04-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetting',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='type',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
