# Generated by Django 3.1.7 on 2021-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210418_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsetting',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
