# Generated by Django 3.2 on 2021-05-20 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210418_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsetting',
            name='value',
        ),
        migrations.CreateModel(
            name='AccountSettingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('accountSetting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.accountsetting')),
            ],
        ),
    ]
